# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znapTg9bTDp6snSIK9oY659oRZp4lohD
"""

# ============================================================
# TASK 04:
# ============================================================

!pip -q install pandas matplotlib seaborn nltk

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

nltk.download("vader_lexicon", quiet=True)

# ------------------------------------------------------------
# 1. LOAD TESLA DATASET
# ------------------------------------------------------------

url = "https://huggingface.co/datasets/hugginglearners/twitter-dataset-tesla/resolve/main/Tesla.csv"

df = pd.read_csv(url)

print("=" * 65)
print("        TESLA SOCIAL MEDIA SENTIMENT ANALYSIS")
print("=" * 65)

print("\nOriginal Dataset")
print("----------------")
print("Rows    :", len(df))
print("Columns :", len(df.columns))


# ------------------------------------------------------------
# 2. DATA CLEANING
# ------------------------------------------------------------

# Keep English tweets
if "language" in df.columns:
    df = df[
        df["language"].astype(str).str.lower() == "en"
    ].copy()

# Remove missing tweets
df = df.dropna(subset=["tweet"])

# Remove duplicate tweets
df = df.drop_duplicates(subset=["tweet"])

print("\nAfter Data Cleaning")
print("-------------------")
print("English tweets :", len(df))


# ------------------------------------------------------------
# 3. TEXT PREPROCESSING
# ------------------------------------------------------------

def clean_text(text):

    text = str(text)

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove mentions
    text = re.sub(r"@\w+", "", text)

    # Remove RT
    text = re.sub(r"\bRT\b", "", text)

    # Remove hashtag symbol
    text = re.sub(r"#", "", text)

    # Convert to lowercase
    text = text.lower()

    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


df["clean_tweet"] = df["tweet"].apply(clean_text)

df = df[
    df["clean_tweet"].str.len() > 0
].copy()


# ------------------------------------------------------------
# 4. SENTIMENT ANALYSIS USING VADER
# ------------------------------------------------------------

analyzer = SentimentIntensityAnalyzer()


def analyze_sentiment(text):

    scores = analyzer.polarity_scores(text)

    compound = scores["compound"]

    if compound >= 0.05:
        sentiment = "Positive"

    elif compound <= -0.05:
        sentiment = "Negative"

    else:
        sentiment = "Neutral"

    return sentiment, compound


results = df["clean_tweet"].apply(analyze_sentiment)

df["sentiment"] = results.apply(lambda x: x[0])
df["compound_score"] = results.apply(lambda x: x[1])


# ------------------------------------------------------------
# 5. SENTIMENT SUMMARY
# ------------------------------------------------------------

order = [
    "Positive",
    "Negative",
    "Neutral"
]

counts = (
    df["sentiment"]
    .value_counts()
    .reindex(order, fill_value=0)
)

percentages = (
    counts / len(df) * 100
).round(2)


print("\n" + "=" * 65)
print("             SENTIMENT ANALYSIS RESULTS")
print("=" * 65)

print(
    f"\nPositive : {counts['Positive']} "
    f"({percentages['Positive']}%)"
)

print(
    f"Negative : {counts['Negative']} "
    f"({percentages['Negative']}%)"
)

print(
    f"Neutral  : {counts['Neutral']} "
    f"({percentages['Neutral']}%)"
)

print("\nTotal analyzed tweets :", len(df))


# ------------------------------------------------------------
# 6. OVERALL SENTIMENT
# ------------------------------------------------------------

average_score = df["compound_score"].mean()

if average_score >= 0.05:
    overall = "Positive"

elif average_score <= -0.05:
    overall = "Negative"

else:
    overall = "Neutral"


print("\nAverage Sentiment Score :", round(average_score, 4))
print("Overall Public Opinion  :", overall)


# ------------------------------------------------------------
# 7. SUMMARY TABLE
# ------------------------------------------------------------

summary = pd.DataFrame({
    "Sentiment": order,
    "Number of Tweets": counts.values,
    "Percentage": percentages.values
})

print("\n" + "=" * 65)
print("                  SUMMARY TABLE")
print("=" * 65)

print(summary.to_string(index=False))


# ------------------------------------------------------------
# 8. BAR CHART
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

sns.barplot(
    x=order,
    y=counts.values
)

plt.title(
    "Tesla Social Media Sentiment Distribution"
)

plt.xlabel("Sentiment")
plt.ylabel("Number of Tweets")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 9. PIE CHART
# ------------------------------------------------------------

plt.figure(figsize=(7, 7))

plt.pie(
    counts.values,
    labels=order,
    autopct="%1.1f%%",
    startangle=90
)

plt.title(
    "Tesla Social Media Sentiment Percentage"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 10. SENTIMENT SCORE DISTRIBUTION
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.hist(
    df["compound_score"],
    bins=20
)

plt.title(
    "Tesla Sentiment Score Distribution"
)

plt.xlabel("Compound Sentiment Score")
plt.ylabel("Number of Tweets")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 11. TOP POSITIVE TWEETS
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("               TOP 5 POSITIVE TWEETS")
print("=" * 65)

positive = (
    df.sort_values(
        "compound_score",
        ascending=False
    )[["tweet", "compound_score"]]
    .head(5)
)

for i, row in enumerate(
    positive.itertuples(index=False),
    1
):
    print(f"\n{i}. {row.tweet}")
    print("   Score:", round(row.compound_score, 3))


# ------------------------------------------------------------
# 12. TOP NEGATIVE TWEETS
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("               TOP 5 NEGATIVE TWEETS")
print("=" * 65)

negative = (
    df.sort_values(
        "compound_score",
        ascending=True
    )[["tweet", "compound_score"]]
    .head(5)
)

for i, row in enumerate(
    negative.itertuples(index=False),
    1
):
    print(f"\n{i}. {row.tweet}")
    print("   Score:", round(row.compound_score, 3))


# ------------------------------------------------------------
# 13. FINAL CONCLUSION
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("                     CONCLUSION")
print("=" * 65)

print(f"""
The sentiment analysis was performed on {len(df)} Tesla-related
social media tweets.

Positive sentiment : {percentages['Positive']}%
Negative sentiment : {percentages['Negative']}%
Neutral sentiment  : {percentages['Neutral']}%

The average compound sentiment score is {average_score:.4f},
indicating an overall {overall.lower()} sentiment in the
analyzed dataset.

The analysis helps identify public opinion towards Tesla by
classifying social-media posts into positive, negative and
neutral categories.

Positive tweets generally express favorable opinions about
Tesla's technology, vehicles and performance, while negative
tweets reflect criticism or dissatisfaction. Neutral tweets
mainly provide information or discussion without strong
emotional language.

Therefore, sentiment analysis provides a useful way to
understand public perception of Tesla on social media.
""")


# ------------------------------------------------------------
# 14. SAVE FINAL DATASET
# ------------------------------------------------------------

df.to_csv(
    "Tesla_Sentiment_Analysis_Final.csv",
    index=False
)

print("=" * 65)
print("Final analyzed dataset saved as:")
print("Tesla_Sentiment_Analysis_Final.csv")
print("=" * 65)